content:
  - name: posts
    label: Posts
    type: collection
    path: 'content'
    view:
      fields: [ title ]
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text