
# media:
#  input: public/images
#  output: /images

media:
  input: content
  output: assets
  categories: [ image ]
content:
  - name: posts
    label: Posts
    type: collection
    path: content
    view:
      fields: [ title ]
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text